import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkGfm from "remark-gfm";
import remarkRehype from "remark-rehype";
import rehypeStringify from "rehype-stringify";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const siteDir = path.join(root, "site");
const postsDir = path.join(siteDir, "blog", "posts");
const outputDir = path.join(siteDir, "blog");
const siteUrl = "https://pawsitivetime.com";

function escapeHtml(value) {
  return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
}

function parsePost(source, filename) {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) throw new Error(`${filename}: missing YAML front matter`);
  const metadata = yaml.load(match[1]);
  for (const field of ["title", "description", "date", "slug", "author", "lang"]) {
    if (!metadata?.[field]) throw new Error(`${filename}: missing ${field}`);
  }
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(metadata.slug)) throw new Error(`${filename}: invalid slug`);
  const date = new Date(metadata.date);
  if (Number.isNaN(date.valueOf())) throw new Error(`${filename}: invalid date`);
  return { ...metadata, date, markdown: match[2] };
}

function externalLinkPolicy() {
  return (tree) => {
    const visit = (node) => {
      if (node?.type === "element" && node.tagName === "a") {
        const href = node.properties?.href;
        if (typeof href === "string" && /^https?:\/\//i.test(href)) {
          const target = new URL(href);
          if (target.hostname !== "pawsitivetime.com" && !target.hostname.endsWith(".pawsitivetime.com")) {
            node.properties.rel = ["nofollow", "noopener", "noreferrer"];
            node.properties.target = "_blank";
          }
        }
      }
      for (const child of node?.children ?? []) visit(child);
    };
    visit(tree);
  };
}

async function renderMarkdown(markdown) {
  return String(await unified().use(remarkParse).use(remarkGfm).use(remarkRehype).use(externalLinkPolicy).use(rehypeStringify).process(markdown));
}

function template({ title, description, canonical, body, data, type = "article" }) {
  return `<!doctype html>
<!-- generated by GitDocs Sync blog builder -->
<html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(description)}" /><link rel="canonical" href="${canonical}" />
<link rel="alternate" type="application/rss+xml" title="GitDocs Sync Blog" href="${siteUrl}/blog/rss.xml" />
<meta property="og:title" content="${escapeHtml(title)}" /><meta property="og:description" content="${escapeHtml(description)}" /><meta property="og:type" content="${type}" /><meta property="og:url" content="${canonical}" /><meta property="og:image" content="${siteUrl}/assets/gitdocs-hero.png" /><meta name="twitter:card" content="summary_large_image" />
<link rel="stylesheet" href="../styles.css" /><script type="application/ld+json">${JSON.stringify(data).replaceAll("<", "\\u003c")}</script></head>
<body><header class="site-header"><a class="brand" href="../index.html">GitDocs Sync</a><nav><a href="./">Blog</a><a href="../index.html#pricing">Pricing</a><a href="../index.html#install">Install</a></nav></header>${body}</body></html>`;
}

function articlePage(post) {
  const canonical = `${siteUrl}/blog/${post.slug}.html`;
  const iso = post.date.toISOString();
  const data = { "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.description, datePublished: iso, dateModified: iso, author: { "@type": "Person", name: post.author }, publisher: { "@type": "Organization", name: "GitDocs Sync", url: siteUrl }, mainEntityOfPage: canonical };
  const body = `<main class="blog-shell"><article><header class="article-header"><p class="eyebrow">${escapeHtml(post.category ?? "Documentation operations")}</p><h1>${escapeHtml(post.title)}</h1><p class="article-description">${escapeHtml(post.description)}</p><p class="article-meta"><time datetime="${iso.slice(0, 10)}">${iso.slice(0, 10)}</time> · ${escapeHtml(post.author)}</p></header><div class="article-body">${post.html}</div><aside class="article-cta"><h2>See what is out of sync before translating</h2><p>Run a dry audit without changing your documentation.</p><a class="button primary" href="../index.html#register">Request a free key</a></aside></article><footer class="blog-footer"><a href="./">← All articles</a> · <a href="rss.xml">RSS</a></footer></main>`;
  return template({ title: `${post.title} | GitDocs Sync`, description: post.description, canonical, body, data });
}

function indexPage(posts) {
  const rows = posts.map((post) => `<article class="post-row"><div><time datetime="${post.date.toISOString().slice(0, 10)}">${post.date.toISOString().slice(0, 10)}</time><br /><span class="post-tag">${escapeHtml(post.category ?? "Docs operations")}</span></div><div><h2><a href="${post.slug}.html">${escapeHtml(post.title)}</a></h2><p>${escapeHtml(post.description)}</p></div></article>`).join("\n");
  const canonical = `${siteUrl}/blog/`;
  const body = `<main class="blog-shell"><header class="blog-header"><p class="eyebrow">GitDocs Sync Blog</p><h1>Multilingual docs, without the drift.</h1><p class="blog-intro">Field notes on Docusaurus localization, translation review, release workflows, and the cost of documentation falling behind.</p></header><section class="post-list">${rows}</section><footer class="blog-footer"><a href="rss.xml">Subscribe via RSS</a></footer></main>`;
  const data = { "@context": "https://schema.org", "@type": "Blog", name: "GitDocs Sync Blog", url: canonical, blogPost: posts.map((post) => ({ "@type": "BlogPosting", headline: post.title, url: `${siteUrl}/blog/${post.slug}.html`, datePublished: post.date.toISOString() })) };
  return template({ title: "GitDocs Sync Blog | Docusaurus localization", description: "Practical guidance for keeping Docusaurus multilingual documentation current.", canonical, body, data, type: "website" });
}

function rss(posts) {
  const items = posts.map((post) => `<item><title>${escapeHtml(post.title)}</title><link>${siteUrl}/blog/${post.slug}.html</link><guid>${siteUrl}/blog/${post.slug}.html</guid><pubDate>${post.date.toUTCString()}</pubDate><description>${escapeHtml(post.description)}</description></item>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0"><channel><title>GitDocs Sync Blog</title><link>${siteUrl}/blog/</link><description>Docusaurus localization and multilingual documentation operations.</description>${items}</channel></rss>\n`;
}

function sitemap(posts) {
  const urls = ["/", "/zh.html", "/payment-success.html", "/zh-payment-success.html", "/blog/", ...posts.map((post) => `/blog/${post.slug}.html`)];
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map((url) => `  <url><loc>${siteUrl}${url}</loc></url>`).join("\n")}\n</urlset>\n`;
}

await fs.mkdir(postsDir, { recursive: true });
const posts = [];
for (const file of (await fs.readdir(postsDir)).filter((name) => name.endsWith(".md"))) {
  const post = parsePost(await fs.readFile(path.join(postsDir, file), "utf8"), file);
  if (post.draft === true) continue;
  post.html = await renderMarkdown(post.markdown);
  posts.push(post);
}
posts.sort((a, b) => b.date - a.date);
const activeOutputs = new Set(["index.html", ...posts.map((post) => `${post.slug}.html`)]);
for (const file of await fs.readdir(outputDir)) {
  if (!file.endsWith(".html") || activeOutputs.has(file)) continue;
  const output = path.join(outputDir, file);
  if ((await fs.readFile(output, "utf8")).includes("generated by GitDocs Sync blog builder")) await fs.unlink(output);
}
for (const post of posts) await fs.writeFile(path.join(outputDir, `${post.slug}.html`), articlePage(post), "utf8");
await fs.writeFile(path.join(outputDir, "index.html"), indexPage(posts), "utf8");
await fs.writeFile(path.join(outputDir, "rss.xml"), rss(posts), "utf8");
await fs.writeFile(path.join(siteDir, "sitemap.xml"), sitemap(posts), "utf8");
console.log(`Built ${posts.length} blog post(s).`);
